CREATE TABLE academy_class (
    class_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name VARCHAR2(100) NOT NULL,
    class_type VARCHAR2(20) NOT NULL CHECK (class_type IN ('REGULAR', 'EXAM_PREP')),
    subject VARCHAR2(100) DEFAULT 'JAVA',
    teacher VARCHAR2(100),
    day_of_week VARCHAR2(20),
    class_time VARCHAR2(30),
    active_yn CHAR(1) DEFAULT 'Y' NOT NULL CHECK (active_yn IN ('Y', 'N')),
    CONSTRAINT uk_academy_class_name UNIQUE (class_name)
);

CREATE TABLE student (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR2(100) NOT NULL,
    school_name VARCHAR2(100),
    parent_name VARCHAR2(100),
    parent_email VARCHAR2(200),
    CONSTRAINT uk_student_name_school UNIQUE (student_name, school_name)
);

CREATE TABLE class_enrollment (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id NUMBER NOT NULL REFERENCES academy_class(class_id),
    student_id NUMBER NOT NULL REFERENCES student(student_id),
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'WITHDRAWN', 'PAUSED')),
    start_date DATE DEFAULT SYSDATE,
    end_date DATE,
    CONSTRAINT uk_enrollment_class_student UNIQUE (class_id, student_id)
);

CREATE TABLE class_session (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id NUMBER NOT NULL REFERENCES academy_class(class_id),
    session_date DATE NOT NULL,
    test_round VARCHAR2(50),
    topic VARCHAR2(200),
    CONSTRAINT uk_session_class_date_round UNIQUE (class_id, session_date, test_round)
);

CREATE TABLE grade_record (
    grade_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id NUMBER NOT NULL REFERENCES class_session(session_id),
    student_id NUMBER NOT NULL REFERENCES student(student_id),
    attendance VARCHAR2(20) CHECK (attendance IN ('출석', '결석')),
    pre_grade VARCHAR2(10),
    weekly_grade VARCHAR2(10),
    test_result VARCHAR2(100),
    CONSTRAINT uk_grade_session_student UNIQUE (session_id, student_id)
);

CREATE TABLE message_template (
    template_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_type VARCHAR2(20) NOT NULL CHECK (class_type IN ('REGULAR', 'EXAM_PREP')),
    template_name VARCHAR2(100) NOT NULL,
    template_content CLOB NOT NULL,
    active_yn CHAR(1) DEFAULT 'Y' NOT NULL CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE send_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER REFERENCES student(student_id),
    session_id NUMBER REFERENCES class_session(session_id),
    parent_email VARCHAR2(200),
    message_content CLOB,
    status VARCHAR2(20) NOT NULL CHECK (status IN ('READY', 'SENT', 'FAILED', 'SKIPPED')),
    sent_at TIMESTAMP,
    error_message VARCHAR2(1000)
);

CREATE TABLE makeup_request (
    makeup_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL REFERENCES student(student_id),
    original_session_id NUMBER NOT NULL REFERENCES class_session(session_id),
    target_session_id NUMBER REFERENCES class_session(session_id),
    status VARCHAR2(20) DEFAULT 'REQUESTED' NOT NULL
        CHECK (status IN ('REQUESTED', 'APPROVED', 'COMPLETED', 'CANCELED'))
);

COMMIT;
